import Head from 'next/head'

import BasicTable from '../components/basicTable'

export default function Home() {
  return (
    <div>
      <Head>
        <title>React-table Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div>

          <BasicTable />

        </div>
      </main>
      
    </div>
  )
}
