import Head from 'next/head'

import BasicTable from '../components/basicTable'
import MOCK_DATA from '../utils/MOCK_DATA.json'

export default function Home({MOCK_DATA}) {
  return (
    <div>
      <Head>
        <title>React-table Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div>

          <BasicTable MOCK_DATA={MOCK_DATA} />

        </div>
      </main>
      
    </div>
  )
}

export const getStaticProps = async (ctx) => {
  return {
    props:{
      MOCK_DATA
    }
  }
}